bdd:
  build: .
  volumes:
    - ./features/:/usr/workplace/features/
  dockerfile: ./bdd.Dockerfile
  command: sh ./bdd_start.sh
  links:
    - app

app:
  build: .
  volumes:
    - ./app/:/usr/workplace/app
  dockerfile: ./app.Dockerfile
  command: sh ./app_start.sh
  ports:
    - "8888:3000"
